[project]
name = "CRD.Analysis.Sid.Rotation"
r_version = "4.5"

# Optional: base URL for `rv add owner/repo` shorthand (defaults to https://github.com).
# git_shorthand_base_url = "https://github.example.com"
# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
    { alias = "P3M-manylinux",    url = "https://packagemanager.posit.co/cran/latest"},
    { alias = "CRAN",             url = "https://cloud.r-project.org/"},
    # { alias = "BioCsoft.23",      url = "https://bioconductor.org/packages/3.23/bioc" },
    # { alias = "BioCann.23",       url = "https://bioconductor.org/packages/3.23/data/annotation" },
    # { alias = "BioCexp.23",       url = "https://bioconductor.org/packages/3.23/data/experiment" },
    # { alias = "BioCworkflows.23", url = "https://bioconductor.org/packages/3.23/workflows" }
    { alias = "BioCsoft.22",      url = "https://bioconductor.org/packages/3.22/bioc" },
    { alias = "BioCann.22",       url = "https://bioconductor.org/packages/3.22/data/annotation" },
    { alias = "BioCexp.22",       url = "https://bioconductor.org/packages/3.22/data/experiment" },
    { alias = "BioCworkflows.22", url = "https://bioconductor.org/packages/3.22/workflows" }
]

# A list of packages to install and any additional configuration
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN"},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
    "variancePartition",
    { name = "decorate", git = "https://github.com/GabrielHoffman/decorate.git", branch = "master" },
    "tidyverse",
    "magrittr",
    "sva",
    "tictoc",
    "GenomicRanges",
    "glue",
    "here",
    "ggplot2",
    "dplyr",
    "edgeR",
]
