---
title: Surrogate Variable Analysis
author: "Siddharth Reed"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    number_sections: true
lightbox: true
format: 
  html:
    fig-width: 6
    fig-height: 4
    code-fold: true
    theme:
      light: flatly
      dark: darkly
---

Set notebook options
```{r knitr_options}
library(knitr)
knitr::opts_chunk$set(
    results=FALSE,
    message=FALSE,
    warning=FALSE,
    # dev=c('png', 'pdf', 'svg'),
    dev=c('png'),
    dpi=300
)
```
Load dependencies
```{r load_dependencies}
library(here)
source(here('scripts', 'locations.R'))
source(here('scripts', 'utils.R'))
source(here('scripts', 'utils.decorate.R'))
source(here('scripts', 'utils.plot.R'))
```

# Load SVs

```{r load_data}
# all.sample.metadata %>% count(AD_CERAD_withDLB)
# all.sample.metadata %>% count(Braak_3levels)
# all.sample.metadata %>% count(CDR_3levels)
all.sample.metadata <- 
    load_sample_metadata()
all.SVs.df <- 
    list_all_SVs() %>%
    mutate(
        SVs.df=
            pmap(
                .l=list(SVs.filepath),
                .f=
                    function(SVs.filepath, sample.metadata) {
                        SVs.filepath %>% 
                        read_tsv(show_col_types=FALSE) %>% 
                        left_join(
                            sample.metadata,
                            by=join_by(SampleID)
                        )
                    },
                sample.metadata=all.sample.metadata
            )
    )
```

# Correlation of SVs and Sample Metadata

```{r plotSV_metadata_correlation}

make_heatmap <- function(SVs.df, model.vars, ...) {
    all.vars <- 
        c(
            model.vars,
            grep('^SV', colnames(SVs.df), value=TRUE)
        )
    SVs.df %>% 
    canCorPairs(
        formula=sprintf('~ %s', paste(all.vars, collapse='+')) %>% formula(),
        data=.
    ) %>%
    as.data.frame() %>% 
    rownames_to_column('Var1') %>% 
    pivot_longer(
        -c(Var1),
        names_to='Var2',
        values_to='corr'
    ) %>% 
    mutate(across(c(Var1, Var2), ~ factor(.x, levels=all.vars))) %>% 
    mutate(corr.label=round(corr, 2)) %>% 
    ggplot(aes(x=Var1, y=Var2, fill=corr)) +
    geom_tile() +
    geom_text(
        aes(label=corr.label), 
        color='white',
        size=2
    ) + 
    make_ggtheme() +
    theme(
        axis.text.x=element_text(angle=45, vjust=1, hjust=1),
        axis.line=element_blank(),
        axis.title=element_blank(),
    )
}
all.SVs.df %>% 
mutate(
    figures=
        pmap(
            .l=.,
            .f=make_heatmap,
            model.vars=c('Braak_3levels', 'CDR_3levels', 'age')
        )
) %>%
pull(figures)
# compartments.df %>% 
    # group_by() %>% 
    # summarize() %>%  # Gb scale
    # ungroup() %>% 
    # calc_pct(col_pct='compartment') %>% 
    # make_nested_plot_tabs(
    #     max.header.lvl=3,
    #     group.cols=c('resolution', 'compartment.params'),
    #     plot.fnc=plot_barplot,
    #     # plot.fnc=plot_violin,
    #     x.var='Edit',
    #     y.var='pct',
    #     y.scale.mode='pct',
    #     fill.var='compartment', 
    #     facet.col='Genotype',
    #     position='stack',
    #     label.var='n.and.pct.label',
    #     scales='free_x',
    #     space='free_x',
    #     # legend.text=element_text(angle=35, hjust=1),
    #     # axis.text.x=element_text(angle=45, hjust=1),
    #     axis.title.x=element_blank(),
    #     axis.title.y=element_blank()
    # )
```

