suppressPackageStartupMessages({
    library(tidyverse)
    library(magrittr)
    library(tictoc)
    library(glue)
    library(furrr)
    library(progressr)
    # library(progressify)
    # library(futurize)
    # library(optparse)
    # library(furrr)
    # library(plyranges)
})
TOTAL_CORES <- length(future::availableWorkers())
source(here('scripts', 'locations.R'))
source(here('scripts', 'constants.R'))
source(here('scripts', 'utils.R'))
